### ISSUE TITLE
Crash with CoFH Core

### ISSUE THREAD

**Issue by JosephFrankFir** [makamys/Neodymium#45]
`neodymium-1.7.10-0.2.1.jar` and `CoFHCore-[1.7.10]3.1.4-329` produces this error:
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/renderer/RenderGlobal.func_72726_b(Ljava/lang/String;DDDDDD)Lnet/minecraft/client/particle/EntityFX; @1913: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[1]) is not assignable to 'net/minecraft/client/particle/EntityFX'
  Current Frame:
    bci: @1913
    flags: { }
    locals: { 'net/minecraft/client/renderer/RenderGlobal', 'java/lang/String', double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, double, double_2nd, integer, double, double_2nd, double, double_2nd, double, double_2nd, 'java/lang/Object', double, double_2nd }
    stack: { 'net/minecraft/client/particle/EffectRenderer', 'java/lang/Object' }
  Bytecode:
    0x0000000: 2ab4 00a9 c607 7b2a b400 a9b4 01e7 c607
    0x0000010: 712a b400 a9b4 0669 c607 672a b400 a9b4
    0x0000020: 018b b406 6c36 0e15 0e04 a000 142a b401
    0x0000030: 59b4 066f 06b6 0672 9a00 0605 360e 2ab4
    0x0000040: 00a9 b401 e7b4 01ec 2867 390f 2ab4 00a9
    0x0000050: b401 e7b4 01f5 1804 6739 112a b400 a9b4
    0x0000060: 01e7 b401 f818 0667 3913 013a 152b 1306
    0x0000070: 74b6 0679 9900 292a b400 a9b4 0669 bb06
    0x0000080: 7b59 2ab4 0159 2818 0418 0618 0818 0a18
    0x0000090: 0cb7 067e 593a 15b6 0684 a700 6b2b 1306
    0x00000a0: 86b6 0679 9900 2d2a b400 a9b4 0669 bb06
    0x00000b0: 8859 2ab4 00b1 2ab4 0159 2818 0418 0618
    0x00000c0: 0818 0a18 0cb7 068b 593a 15b6 0684 a700
    0x00000d0: 372b 1306 8db6 0679 9900 2d2a b400 a9b4
    0x00000e0: 0669 bb06 8f59 2ab4 0159 2818 0418 0618
    0x00000f0: 0818 0a18 0c2a b400 a9b4 0669 b706 9259
    0x0000100: 3a15 b606 8419 15c6 0006 1915 b014 0341
    0x0000110: 3916 180f 180f 6b18 1118 116b 6318 1318
    0x0000120: 136b 6318 1618 166b 979e 0005 01b0 150e
    0x0000130: 04a4 0005 01b0 2b13 0694 b606 7999 001e
    0x0000140: bb06 9659 2ab4 0159 2818 0418 0618 0818
    0x0000150: 0a18 0cb7 0697 3a15 a706 132b 1306 99b6
    0x0000160: 0679 9900 1ebb 069b 592a b401 5928 1804
    0x0000170: 1806 1808 180a 180c b706 9c3a 15a7 05ee
    0x0000180: 2b13 069e b606 7999 001e bb06 a059 2ab4
    0x0000190: 0159 2818 0418 0618 0818 0a18 0cb7 06a1
    0x00001a0: 3a15 a705 c92b 1306 a3b6 0679 9900 1ebb
    0x00001b0: 06a0 592a b401 5928 1804 1806 1808 180a
    0x00001c0: 180c b706 a13a 15a7 05a4 2b13 06a5 b606
    0x00001d0: 7999 001e bb06 a759 2ab4 0159 2818 0418
    0x00001e0: 0618 0818 0a18 0cb7 06a8 3a15 a705 7f2b
    0x00001f0: 1306 aab6 0679 9900 3fbb 06a7 592a b401
    0x0000200: 5928 1804 1806 1808 180a 180c b706 a83a
    0x0000210: 1519 1519 15b6 06af 1306 b06a 1915 b606
    0x0000220: b313 04c2 6a19 15b6 06b6 b606 b919 15b6
    0x0000230: 06bc a705 392b 1306 beb6 0679 9900 1ebb
    0x0000240: 06c0 592a b401 5928 1804 1806 1808 180a
    0x0000250: 180c b706 c13a 15a7 0514 2b13 06c3 b606
    0x0000260: 7999 0029 bb06 c559 2ab4 0159 2818 0418
    0x0000270: 060e 0e0e b706 c63a 1519 1518 0890 180a
    0x0000280: 9018 0c90 b606 b9a7 04e4 2b13 06c8 b606
    0x0000290: 7999 0031 bb06 c559 2ab4 0159 2818 0418
    0x00002a0: 060e 0e0e b706 c63a 1519 1513 011c b606
    0x00002b0: cb19 1518 0890 180a 9018 0c90 b606 b9a7
    0x00002c0: 04ac 2b13 06cd b606 7999 001e bb06 c559
    0x00002d0: 2ab4 0159 2818 0418 0618 0818 0a18 0cb7
    0x00002e0: 06c6 3a15 a704 872b 1306 cfb6 0679 9900
    0x00002f0: 29bb 06c5 592a b401 5928 1804 1806 1808
    0x0000300: 180a 180c b706 c63a 1519 15c0 06c5 1100
    0x0000310: 90b6 06d2 a704 572b 1306 d4b6 0679 9900
    0x0000320: 4ebb 06c5 592a b401 5928 1804 1806 1808
    0x0000330: 180a 180c b706 c63a 1519 15c0 06c5 1100
    0x0000340: 90b6 06d2 2ab4 0159 b406 6fb6 011b 1304
    0x0000350: d86a 1306 d562 3818 1915 0c17 186a 0b17
    0x0000360: 186a 0c17 186a b606 b9a7 0402 2b13 06d7
    0x0000370: b606 7999 001e bb06 d959 2ab4 0159 2818
    0x0000380: 0418 0618 0818 0a18 0cb7 06da 3a15 a703
    0x0000390: dd2b 1306 dcb6 0679 9900 1ebb 06de 592a
    0x00003a0: b401 5928 1804 1806 1808 180a 180c b706
    0x00003b0: df3a 15a7 03b8 2b13 06e1 b606 7999 001e
    0x00003c0: bb06 e359 2ab4 0159 2818 0418 0618 0818
    0x00003d0: 0a18 0cb7 06e4 3a15 a703 932b 1306 e6b6
    0x00003e0: 0679 9900 1ebb 06e8 592a b401 5928 1804
    0x00003f0: 1806 1808 180a 180c b706 e93a 15a7 036e
    0x0000400: 2b13 06eb b606 7999 001e bb06 ed59 2ab4
    0x0000410: 0159 2818 0418 0618 0818 0a18 0cb7 06ee
    0x0000420: 3a15 a703 492b 1306 f0b6 0679 9900 18bb
    0x0000430: 06f2 592a b401 5928 1804 1806 b706 f53a
    0x0000440: 15a7 032a 2b13 06f7 b606 7999 001c bb06
    0x0000450: f959 2ab4 00b1 2ab4 0159 2818 0418 06b7
    0x0000460: 06fc 3a15 a703 072b 1306 feb6 0679 9900
    0x0000470: 1ebb 0700 592a b401 5928 1804 1806 1808
    0x0000480: 180a 180c b707 013a 15a7 02e2 2b13 0703
    0x0000490: b606 7999 001e bb07 0559 2ab4 0159 2818
    0x00004a0: 0418 0618 0818 0a18 0cb7 0706 3a15 a702
    0x00004b0: bd2b 1307 08b6 0679 9900 21bb 06c0 592a
    0x00004c0: b401 5928 1804 1806 1808 180a 180c 1307
    0x00004d0: 09b7 070c 3a15 a702 952b 1307 0eb6 0679
    0x00004e0: 9900 1ebb 0710 592a b401 5928 1804 1806
    0x00004f0: 1808 180a 180c b707 113a 15a7 0270 2b13
    0x0000500: 0713 b606 7999 0021 bb07 1559 2ab4 0159
    0x0000510: 2818 0418 0618 0890 180a 9018 0c90 b707
    0x0000520: 183a 15a7 0248 2b13 071a b606 7999 001b
    0x0000530: bb07 1c59 2ab4 0159 2818 0418 06b2 0722
    0x0000540: b707 253a 15a7 0226 2b13 0727 b606 7999
    0x0000550: 001b bb07 2959 2ab4 0159 2818 0418 06b2
    0x0000560: 072c b707 2f3a 15a7 0204 2b13 0731 b606
    0x0000570: 7999 001b bb07 2959 2ab4 0159 2818 0418
    0x0000580: 06b2 0734 b707 2f3a 15a7 01e2 2b13 0736
    0x0000590: b606 7999 001e bb07 3859 2ab4 0159 2818
    0x00005a0: 0418 0618 0818 0a18 0cb7 0739 3a15 a701
    0x00005b0: bd2b 1307 3bb6 0679 9900 1bbb 071c 592a
    0x00005c0: b401 5928 1804 1806 b207 3eb7 0725 3a15
    0x00005d0: a701 9b2b 1307 40b6 0679 9900 1ebb 0742
    0x00005e0: 592a b401 5928 1804 1806 1808 180a 180c
    0x00005f0: b707 433a 15a7 0176 2b13 0745 b606 7999
    0x0000600: 0031 bb07 4259 2ab4 0159 2818 0414 0746
    0x0000610: 6318 0618 0818 0a18 0cb7 0743 3a15 1915
    0x0000620: 1051 b607 4a19 150c 0c0c b606 b9a7 013e
    0x0000630: 2b13 074c b606 7999 002d bb06 a059 2ab4
    0x0000640: 0159 2818 0418 0618 0818 0a18 0cb7 06a1
    0x0000650: 3a15 1915 1052 b607 4a19 150c 0c0c b606
    0x0000660: b9a7 010a 2b13 074e b607 5299 0069 2b13
    0x0000670: 0754 06b6 0758 3a19 1919 0432 b807 5e36
    0x0000680: 1a19 19be 05a4 002e 1919 0532 b807 5e36
    0x0000690: 18bb 071c 592a b401 5928 1804 1806 1808
    0x00006a0: 180a 180c 151a b807 6415 18b7 0767 3a15
    0x00006b0: a700 21bb 071c 592a b401 5928 1804 1806
    0x00006c0: 1808 180a 180c 151a b807 6403 b707 673a
    0x00006d0: 15a7 009a 2b13 0769 b607 5299 0046 2b13
    0x00006e0: 0754 06b6 0758 3a19 1919 0432 b807 5eb8
    0x00006f0: 076d 3a1a 1919 0532 b807 5e36 18bb 076f
    0x0000700: 592a b401 5928 1804 1806 1808 180a 180c
    0x0000710: 191a 1518 b707 7215 18b6 0776 3a15 a700
    0x0000720: 4d2b 1307 78b6 0752 9900 432b 1307 5406
    0x0000730: b607 583a 1919 1904 32b8 075e b807 6d3a
    0x0000740: 1a19 1905 32b8 075e 3618 bb07 7a59 2ab4
    0x0000750: 0159 2818 0418 0618 0818 0a18 0c19 1a15
    0x0000760: 18b7 077b 1518 b607 7c3a 1519 15c6 000f
    0x0000770: 2ab4 00a9 b406 6919 15b6 0684 1915 b001
    0x0000780: b0                                     
  Stackmap Table:
    append_frame(@62,Integer)
    full_frame(@157,{Object[#2],Object[#1654],Double,Double,Double,Double,Double,Double,Integer,Double,Double,Double,Null},{})
    same_frame(@209)
    full_frame(@261,{Object[#2],Object[#1654],Double,Double,Double,Double,Double,Double,Integer,Double,Double,Double,Object[#1708]},{})
    same_frame(@269)
    append_frame(@302,Double)
    same_frame(@310)
    same_frame(@347)
    same_frame(@384)
    same_frame(@421)
    same_frame(@458)
    same_frame(@495)
    same_frame_extended(@565)
    same_frame(@602)
    same_frame(@650)
    same_frame(@706)
    same_frame(@743)
    same_frame(@791)
    same_frame_extended(@876)
    same_frame(@913)
    same_frame(@950)
    same_frame(@987)
    same_frame(@1024)
    same_frame(@1061)
    same_frame(@1092)
    same_frame(@1127)
    same_frame(@1164)
    same_frame(@1201)
    same_frame(@1241)
    same_frame(@1278)
    same_frame(@1318)
    same_frame(@1352)
    same_frame(@1386)
    same_frame(@1420)
    same_frame(@1457)
    same_frame(@1491)
    same_frame(@1528)
    same_frame(@1584)
    same_frame(@1636)
    append_frame(@1715,Top,Object[#1928],Integer)
    full_frame(@1745,{Object[#2],Object[#1654],Double,Double,Double,Double,Double,Double,Integer,Double,Double,Double,Object[#1820],Double,Top,Object[#1928],Integer},{})
    full_frame(@1748,{Object[#2],Object[#1654],Double,Double,Double,Double,Double,Double,Integer,Double,Double,Double,Object[#1708],Double},{})
    same_frame_extended(@1825)
    full_frame(@1899,{Object[#2],Object[#1654],Double,Double,Double,Double,Double,Double,Integer,Double,Double,Double,Object[#5],Double},{})
    same_frame(@1916)
    full_frame(@1919,{Object[#2],Object[#1654],Double,Double,Double,Double,Double,Double},{})

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:538)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by makamys** [comment]
Can't reproduce this, please post a full log (`fml-client-latest.log`) if it happens again.
