### ISSUE TITLE
Crash with `java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker`

### ISSUE THREAD

**Issue by saberwoo** [makamys/Neodymium#52]
well the game seems to crash whenever i try to lunch it with the mod on i tested with other lunchers samething migh be a java issue but im not sure here to seek confirmation and help
also first time instaling the mod and im using it to fix the graphic issue anyways here the crash report

```
UltimMC version: 0.7.0-custom


Launched instance in offline mode

Minecraft folder is:
C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/instances/1.7.10/.minecraft


Java path is:
C:/Program Files/Java/jre-1.8/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_401, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/instances/1.7.10/natives

Libraries:
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] CoreTweaks-1.7.10-0.3.3.2+nomixin.jar
  [✔️] neodymium-1.7.10-0.2.3+nomixin.jar

Params:
  --username  --version 1.7.10 --gameDir C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/instances/1.7.10/.minecraft --assetsDir C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-javaagent:C:/Users/GSI Bedjaoui/Desktop/jeu/Nouveau dossier/mmc/injectors/authlib-injector-1.2.5.jar=http://localhost:59245, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx5760m, -Duser.language=en]


Minecraft process ID: 8312


[authlib-injector] [INFO] Logging file: C:\Users\GSI Bedjaoui\Desktop\jeu\Nouveau dossier\mmc\instances\1.7.10\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.5
[authlib-injector] [INFO] Authentication server: http://localhost:59245
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

[16:50:16] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:50:16] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[16:50:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[16:50:16] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[16:50:16] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_401, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre-1.8
[16:50:16] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from CoreTweaks-1.7.10-0.3.3.2+nomixin.jar
[16:50:16] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from neodymium-1.7.10-0.2.3+nomixin.jar
[16:50:16] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:50:16] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[16:50:16] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_401]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_401]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_401]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_401]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_401]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_401]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_401]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[16:50:16] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:217]: Failed to start Minecraft:
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[16:50:16] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 5
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[16:50:16] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 06 Mar 2024 16:50:47 +0100
```

**Comment by makamys** [comment]
> java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker

You're lacking a mixin loader. [UniMixins](https://github.com/LegacyModdingMC/UniMixins) is most likely what you want.
(This is explained in more detail in the "[About `+nomixin` builds](https://github.com/makamys/Neodymium?tab=readme-ov-file#about-nomixin-builds)" section of the readme.)

**Comment by saberwoo** [comment]
thanks
